base_url = "https://akshat-512.github.io/"
title = "Akshat's Log"
description = "A small personal feed for music, films, books, and thoughts on everything else I think about."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
generate_feeds = true


taxonomies = [
    { name = "tags", feed = true },
]

[markdown.highlighting]
style = "class"
dark_theme = "material-theme-palenight"
light_theme = "everforest-light"

[extra]
# Put all your custom variables here
list_pages = true

header_nav = [
    { name = "Archive", url = "/archive/" },
    { name = "Essays", url = "/articles/" },
    { name = "Music", url = "/music/" },
    { name = "Movies", url = "/movies/" },
    { name = "Books", url = "/books/" },
    { name = "Links", url = "/links/" },
]

footer_nav = []

profile_links = [
    { name = "RateYourMusic", url = "https://rateyourmusic.com/~Tablefan", icon = "https://www.google.com/s2/favicons?domain=rateyourmusic.com&sz=64" },
    { name = "Last.fm", url = "https://www.last.fm/user/Z512", icon = "https://www.google.com/s2/favicons?domain=last.fm&sz=64" },
    { name = "Goodreads", url = "https://www.goodreads.com/user/show/68893351-akshat-singhai", icon = "https://www.google.com/s2/favicons?domain=goodreads.com&sz=64" },
    { name = "Letterboxd", url = "https://letterboxd.com/akshat9512/", icon = "https://www.google.com/s2/favicons?domain=letterboxd.com&sz=64" },
]

add_toc = true
