base_url = "https://akshat-512.github.io/"
title = "Akshat Singhai"
description = "Writing about music, films, books, and whatever else pulls focus."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
generate_feeds = true


taxonomies = [
    { name = "tags", feed = true },
]

[markdown.highlighting]
style = "class"
dark_theme = "material-theme-palenight"
light_theme = "everforest-light"

[extra]
# Put all your custom variables here
list_pages = true

header_nav = [
    { name = "~home", url = "/" },
    { name = "articles", url = "/articles/" },
    { name = "movies", url = "/movies/" },
    { name = "music", url = "/music/" },
    { name = "literature", url = "/books/" },
    { name = "#links", url = "/tags/" },
]

footer_nav = [
    { name = "rss", url = "/atom.xml" },
]


add_toc = true
